--
-- PostgreSQL database dump
--

\restrict o1aqjdgYKMzsgfjtEdaDgvSQWVyl3aIO6P6L2hfuOWb9korV9I5T4ozifI95ub3

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: postgis; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS postgis WITH SCHEMA public;


--
-- Name: EXTENSION postgis; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION postgis IS 'PostGIS geometry and geography spatial types and functions';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: anomaly; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.anomaly (
    id uuid NOT NULL default gen_random_uuid (),
    timezone text NOT NULL,
    series_name text NOT NULL,
    site text NOT NULL,
    start_time timestamp with time zone NOT NULL,
    end_time timestamp with time zone NOT NULL,
    location public.geography(Point,4326) NOT NULL,
    cover_photo text NOT NULL
);


ALTER TABLE public.anomaly OWNER TO postgres;

--
-- Name: beacon_battles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.beacon_battles (
    id bigint NOT NULL,
    "time" timestamp with time zone NOT NULL,
    value numeric NOT NULL
);


ALTER TABLE public.beacon_battles OWNER TO postgres;

--
-- Name: beacon_battles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.beacon_battles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.beacon_battles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: distance_walked; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.distance_walked (
    id bigint NOT NULL,
    "time" timestamp with time zone NOT NULL,
    value numeric NOT NULL
);


ALTER TABLE public.distance_walked OWNER TO postgres;

--
-- Name: distance_walked_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.distance_walked ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.distance_walked_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: gamelog; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.gamelog (
    id bigint NOT NULL,
    event_time timestamp with time zone NOT NULL,
    action text NOT NULL,
    comment text,
    location public.geography(Point,4326)
);


ALTER TABLE public.gamelog OWNER TO postgres;

--
-- Name: gamelog_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.gamelog ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.gamelog_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: medals; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.medals (
    id bigint NOT NULL,
    attained_at timestamp with time zone NOT NULL,
    medal_name text NOT NULL,
    is_vanity boolean NOT NULL,
    is_year_badge boolean NOT NULL
);


ALTER TABLE public.medals OWNER TO postgres;

--
-- Name: medals_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.medals ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.medals_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mind_units_controlled; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.mind_units_controlled (
    id bigint NOT NULL,
    "time" timestamp with time zone NOT NULL,
    value numeric NOT NULL
);


ALTER TABLE public.mind_units_controlled OWNER TO postgres;

--
-- Name: mind_units_controlled_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.mind_units_controlled ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mind_units_controlled_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: overclock_glyph_hack_points; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.overclock_glyph_hack_points (
    id bigint NOT NULL,
    "time" timestamp with time zone NOT NULL,
    value numeric NOT NULL
);


ALTER TABLE public.overclock_glyph_hack_points OWNER TO postgres;

--
-- Name: overclock_glyph_hack_points_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.overclock_glyph_hack_points ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.overclock_glyph_hack_points_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: portal_held_days; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.portal_held_days (
    id bigint NOT NULL,
    "time" timestamp with time zone NOT NULL,
    value numeric NOT NULL
);


ALTER TABLE public.portal_held_days OWNER TO postgres;

--
-- Name: portal_held_days_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.portal_held_days ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.portal_held_days_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: portal_history; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.portal_history (
    id bigint NOT NULL,
    type text NOT NULL,
    location public.geography(Point,4326) NOT NULL
);


ALTER TABLE public.portal_history OWNER TO postgres;

--
-- Name: store_purchases; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.store_purchases (
    id text NOT NULL,
    "time" timestamp with time zone NOT NULL,
    transaction_type text NOT NULL,
    item text NOT NULL,
    new_cmu_balance text NOT NULL,
    transaction_description text NOT NULL
);


ALTER TABLE public.store_purchases OWNER TO postgres;

--
-- Name: xm_recharged; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.xm_recharged (
    id bigint NOT NULL,
    "time" timestamp with time zone NOT NULL,
    value numeric NOT NULL
);


ALTER TABLE public.xm_recharged OWNER TO postgres;

--
-- Name: xm_recharged_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.xm_recharged ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.xm_recharged_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: anomaly anomaly_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.anomaly
    ADD CONSTRAINT anomaly_pkey PRIMARY KEY (id);


--
-- Name: beacon_battles beacon_battles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.beacon_battles
    ADD CONSTRAINT beacon_battles_pkey PRIMARY KEY (id);


--
-- Name: distance_walked distance_walked_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.distance_walked
    ADD CONSTRAINT distance_walked_pkey PRIMARY KEY (id);


--
-- Name: gamelog gamelog_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.gamelog
    ADD CONSTRAINT gamelog_pkey PRIMARY KEY (id);


--
-- Name: medals medals_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.medals
    ADD CONSTRAINT medals_pkey PRIMARY KEY (id);


--
-- Name: mind_units_controlled mind_units_controlled_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.mind_units_controlled
    ADD CONSTRAINT mind_units_controlled_pkey PRIMARY KEY (id);


--
-- Name: overclock_glyph_hack_points overclock_glyph_hack_points_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.overclock_glyph_hack_points
    ADD CONSTRAINT overclock_glyph_hack_points_pkey PRIMARY KEY (id);


--
-- Name: portal_held_days portal_held_days_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.portal_held_days
    ADD CONSTRAINT portal_held_days_pkey PRIMARY KEY (id);


--
-- Name: portal_history portal_history_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.portal_history
    ADD CONSTRAINT portal_history_pkey PRIMARY KEY (id);


--
-- Name: store_purchases store_purchases_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.store_purchases
    ADD CONSTRAINT store_purchases_pkey PRIMARY KEY (id);


--
-- Name: xm_recharged xm_recharged_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.xm_recharged
    ADD CONSTRAINT xm_recharged_pkey PRIMARY KEY (id);


--
-- Name: idx_gamelog_action_time; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_gamelog_action_time ON public.gamelog USING btree (action, event_time);


--
-- Name: idx_gamelog_location; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_gamelog_location ON public.gamelog USING gist (location);


--
-- Name: idx_mind_units_time; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_mind_units_time ON public.mind_units_controlled USING btree ("time");


--
-- Name: idx_portal_history_geom; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_portal_history_geom ON public.portal_history USING gist (location);


--
-- PostgreSQL database dump complete
--

\unrestrict o1aqjdgYKMzsgfjtEdaDgvSQWVyl3aIO6P6L2hfuOWb9korV9I5T4ozifI95ub3

